plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'LowCodeMod'
description = 'Language provider for Minecraft Forge that loads mods without a Java entrypoint.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
}

convention.manifest('net/minecraftforge/fml/lowcodemod/', [
    'Automatic-Module-Name': 'net.minecraftforge.lowcodemod',
    'FMLModType'           : 'LANGPROVIDER'
])

convention.publish()