plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'JavaFMLMod'
description = 'Language provider for Minecraft Forge that provides basic Java mod functionality.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
    implementation libs.unsafe
    implementation libs.securemodules
}

convention.manifest('net/minecraftforge/fml/javafmlmod/', [
    'Automatic-Module-Name': 'net.minecraftforge.javafmlmod',
    'FMLModType'           : 'LANGPROVIDER'
])

convention.publish()