plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'MCLanguage'
description = 'Language provider for Minecraft Forge that provides Minecraft Itself.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
}

convention.manifest('net/minecraftforge/fml/mclanguageprovider/', [
    'Automatic-Module-Name': 'net.minecraftforge.mclanguageprovider',
    'FMLModType'           : 'LANGPROVIDER'
])

convention.publish()
